name : My First Workflow

on:  push

jobs:
  
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: print message
        run: echo "Hello, GitHub Action!"

      - name: print Names
        run: echo "Hello,Sahil here!"

  say-bye:
    runs-on: ubuntu-latest

    steps:
      - name: print message
        run: echo "Goodbye from second job"