# name : My First Workflow

# on: [push, pull_request]

# jobs:
  
#   say-hello:
#     runs-on: ubuntu-latest

#     steps:
#       - name: print message
#         run: echo "Hello, GitHub Action!"

#       - name: print Names
#         run: echo "Hello,Sahil this side!"

#   say-bye:
#     runs-on: ubuntu-latest

#     steps:
#       - name: print message
#         run: echo "Goodbye from second job Sir"-

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Run test step 1
        run: echo "Test is running"

      - name: Run test step 2
        run: echo "Test Successful"

  deploy-app:
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy step
        run: echo "Deploying application..."