name : My First Workflow

on: [push, pull_request]

jobs:
  
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: print message
        run: echo "Hello, GitHub Action!"

      - name: print Names
        run: echo "Hello,Sahil this side!"

  say-bye:
    runs-on: ubuntu-latest

    steps:
      - name: print message
        run: echo "Goodbye from second job Sir"